packages:
  - apps/*
  - packages/*
  - tests

allowBuilds:
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.111.0'
  - '@supabase/functions-js@2.111.0'
  - '@supabase/postgrest-js@2.111.0'
  - '@supabase/realtime-js@2.111.0'
  - '@supabase/storage-js@2.111.0'
  - '@supabase/supabase-js@2.111.0'
  - jsdom@30.0.1
